### ISSUE TITLE
after clicking link, the open with dialog is opening and I can't select any app

### ISSUE THREAD

**Issue by DaPeace** [Tensai75/nzb-monkey-go#24]
I installed a blank Ubuntu 22 Desktop.
After setting up nzbmonkey-go, when clicking a nzblnk it only opens the "open with" dialog and I can't find any solution how to start nzbmonkey-go.

Thanks for help!

**Comment by nzb-tuxxx** [comment]
After installing the .deb run `nzb-monkey-go --register` from command line

**Comment by jpoggi** [comment]
Hi,

Try creating this file

`~/.local/share/applications/mimeinfo.cache`

with this content:

`
[MIME Cache]
x-scheme-handler/nzblnk=nzblnk.desktop;
`

You can also verify this file:

`~/.local/share/applications/nzblnk.desktop`

with this content:

`[Desktop Entry]
Type=Application
Name=NZBlnk
Exec=/usr/bin/gnome-terminal --hide-menubar --geometry=100x16 --working-directory="/usr/bin" -e "/usr/bin/nzb-monkey-go %u"
Path=/usr/bin
MimeType=x-scheme-handler/nzblnk;
NoDisplay=true
Terminal=false`

**Comment by prime0n** [comment]
> I installed a blank Ubuntu 22 Desktop.
After setting up nzbmonkey-go, when clicking a nzblnk it only opens the "open with" dialog and I can't find any solution how to start nzbmonkey-go.
Thanks for help!

Can confirm. I have the same behave on a VirtualBox Linux (Kubuntu 23) VM (Win Host)
No association after '--register' call

> After installing the .deb run `nzb-monkey-go --register` from command line

Doesn't help at all. 
I have tried several times in different locations (same with the ZIP version, with previouse purge of the *.deb version).

>Hi,
Try creating this file
~/.local/share/applications/mimeinfo.cache
with this content:
[MIME Cache] x-scheme-handler/nzblnk=nzblnk.desktop;
You can also verify this file:
~/.local/share/applications/nzblnk.desktop
with this content:
[Desktop Entry] Type=Application Name=NZBlnk Exec=/usr/bin/gnome-terminal --hide-menubar --geometry=100x16 --working-directory="/usr/bin" -e "/usr/bin/nzb-monkey-go %u" Path=/usr/bin MimeType=x-scheme-handler/nzblnk; NoDisplay=true Terminal=false

~/.local/share/applications/mimeinfo.cache is missing after '--register' call. I have created it manually, but without success.

~/.local/share/applications/nzblnk.desktop is present but seems diffrent because i do not use gnome. Maybe a new KDE Terminal issue?
